# common_steps.yml
name: Common Steps
on:
  workflow_run:
    workflows: ["Test and Deploy Project"]
    types:
      - completed

jobs:
  common_steps:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18
      - name: Install npm dependencies
        run: npm ci
