name: Test and Deploy Project
on: push

# Define a reusable job template
jobs:
  common_steps:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Install Node js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install npm dependencies
        run: npm ci

  test:
    runs-on: ubuntu-latest
    needs: common_steps
    steps:
      - name: Run tests
        run: npm test

  deploy:
    runs-on: ubuntu-latest
    needs: common_steps
    steps:
      - name: Build Project
        run: npm run build
      - name: Deploy
        run: echo "Deploying ...."
